import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "This is Product Page",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div>
            {children}
            This is magic of Layout hhahahahahah
        </div>
    );
}