import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "My Next.js App", // this is default 
    template: "%s | Soham Patel", // this is for chlid component's metadata extention
  },
  description: "Generated by create next app",
};


// this is layout page this deside the layout of the page and it takes children as a parameter and it automatlly takes page.tsx as children
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className=" bg-amber-400 p-4">
          Soham Patel
        </header>
        {children}
        <footer className=" bg-violet-400 p-4">
          Soham Patel
        </footer>
      </body>
    </html>
  );
}
